repos:
  - repo: local
    hooks:
    - id: run-lint
      name: Run Tox Lint Environment
      entry: tox
      language: system
      pass_filenames: false
      types: [python]
      args: ['-e', 'lint']  # Specify the 'lint' environment
