# This file defines charm config options, and populates the Configure tab on Charmhub.
# If your charm does not require configuration options, delete this file entirely.
#
# See https://juju.is/docs/config for guidance.

options:
  use-email:
    description: |
      A boolean value indicating if you want to use an email for expiry notifications (see email config option).

      If this is set to true and there is no email configured the charm will wait for an email to
      be set in the config before issuing a certificate. If set to false, no email is required to start
      issuing certificates.

    default: true
    type: boolean

  email:
    description: |
      Configures the email used for registering with the certificate provider.

      This is the email to which you will get certificate expiring notices and if you have
      registered with a provider it is the account email. Please also see the use-email config
      option.

    default: ""
    type: string

  server:
    description: |
      Configures the ACME server directory URL.

      Please see some supported here https://github.com/acmesh-official/acme.sh/wiki/Server
      Any other RFC8555-compliant CA should also be supported.

      Currently supported are letsencrypt, letsencrypt_test, zerossl and Any other RFC8555-compliant CA should also be supported
      as long as it does not require any authentication or eab keys.

    default: "zerossl"
    type: string
    