# This file defines charm config options, and populates the Configure tab on Charmhub.
# If your charm does not require configuration options, delete this file entirely.
#
# See https://juju.is/docs/config for guidance.

options:
  email:
    description: |
      Configures the email used for registering with the certificate provider.

      REQUIRED

    default: ""
    type: string

  server:
    description: |
      Configures the ACME server directory URL.

      Please see some supported here https://github.com/acmesh-official/acme.sh/wiki/Server
      Any other RFC8555-compliant CA should also be supported.

      The default CA is zerossl.

    default: "zerossl"
    type: string
    