# Copyright 2023 Martwall
# See LICENSE file for licensing details.
name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - dev
jobs:
  unit-test:
    name: Format, lint and unit test
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install tox
        run: python3 -m pip install tox
      - name: Set PYTHONPATH relative to repository root
        run: echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/lib" >> $GITHUB_ENV
      - name: Run format, lint and unit tests
        run: tox run -e unit
